package main

import (
	"bytes"
	"flag"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func main() {
	typ := flag.String("type", "", "struct type name to generate converters for")
	out := flag.String("output", "", "output file; default zconvert_<type>.go")
	file := flag.String("file", "", "source file; default GOFILE or all .go files in cwd")
	flag.Parse()
	if *typ == "" {
		log.Fatal("-type is required")
	}
	files := []string{}
	if *file != "" {
		files = append(files, *file)
	} else if gf := os.Getenv("GOFILE"); gf != "" {
		files = append(files, gf)
	} else {
		matches, _ := filepath.Glob("*.go")
		for _, m := range matches {
			if !strings.HasSuffix(m, "_test.go") && !strings.HasPrefix(filepath.Base(m), "zconvert_") {
				files = append(files, m)
			}
		}
	}
	if len(files) == 0 {
		log.Fatal("no input files")
	}
	var st *ast.StructType
	pkg := "main"
	for _, f := range files {
		structs, p, err := parseStructTypes(f)
		if err != nil {
			log.Fatal(err)
		}
		if p != "" {
			pkg = p
		}
		if s := structs[*typ]; s != nil {
			st = s
			break
		}
	}
	if st == nil {
		log.Fatalf("type %s not found", *typ)
	}
	code := generate(pkg, *typ, st)
	formatted, err := format.Source(code)
	if err != nil {
		os.Stderr.Write(code)
		log.Fatal(err)
	}
	name := *out
	if name == "" {
		name = "zconvert_" + strings.ToLower(*typ) + ".go"
	}
	if err := os.WriteFile(name, formatted, 0644); err != nil {
		log.Fatal(err)
	}
}

func parseStructTypes(filename string) (map[string]*ast.StructType, string, error) {
	fs := token.NewFileSet()
	f, err := parser.ParseFile(fs, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, "", err
	}
	out := map[string]*ast.StructType{}
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			if st, ok := ts.Type.(*ast.StructType); ok {
				out[ts.Name.Name] = st
			}
		}
	}
	return out, f.Name.Name, nil
}

func generate(pkg, typ string, st *ast.StructType) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by convertgen; DO NOT EDIT.\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import conv \"github.com/oarkflow/convert\"\n\n")
	b.WriteString("func Convert" + typ + "(src map[string]any) (" + typ + ", error) { var out " + typ + "; err := Populate" + typ + "(&out, src); return out, err }\n\n")
	b.WriteString("func Populate" + typ + "(dst *" + typ + ", src map[string]any) error {\n")
	b.WriteString("if dst == nil { return conv.ErrNil }\n")
	for _, f := range st.Fields.List {
		if len(f.Names) == 0 {
			continue
		}
		for _, n := range f.Names {
			if !n.IsExported() {
				continue
			}
			field := n.Name
			key := tagName(f, snakeNameLocal(field))
			ts := exprString(f.Type)
			b.WriteString("if v, ok := src[\"" + key + "\"]; ok {\n")
			emitAssign(&b, field, ts)
			b.WriteString("} else {\n")
			if def := defaultTag(f); def != "" {
				b.WriteString("v := \"" + escape(def) + "\"\n")
				emitAssign(&b, field, ts)
			}
			b.WriteString("}\n")
		}
	}
	b.WriteString("return nil\n}\n")
	return b.Bytes()
}
func emitAssign(b *bytes.Buffer, field, ts string) {
	switch ts {
	case "bool":
		b.WriteString("x, err := conv.ToBool(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindBool, v, err) }; dst." + field + " = x\n")
	case "string":
		b.WriteString("x, err := conv.ToString(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindString, v, err) }; dst." + field + " = x\n")
	case "int":
		b.WriteString("x, err := conv.ToInt(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindInt, v, err) }; dst." + field + " = x\n")
	case "int64":
		b.WriteString("x, err := conv.ToInt64(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindInt, v, err) }; dst." + field + " = x\n")
	case "uint64":
		b.WriteString("x, err := conv.ToUint64(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindUint, v, err) }; dst." + field + " = x\n")
	case "float64":
		b.WriteString("x, err := conv.ToFloat64(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindFloat, v, err) }; dst." + field + " = x\n")
	case "time.Duration":
		b.WriteString("x, err := conv.ToDuration(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindDuration, v, err) }; dst." + field + " = x\n")
	case "time.Time":
		b.WriteString("x, err := conv.ToTime(v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindTime, v, err) }; dst." + field + " = x\n")
	default:
		if strings.HasPrefix(ts, "[]") {
			elem := strings.TrimPrefix(ts, "[]")
			if isTarget(elem) {
				b.WriteString("x, err := conv.ToSlice[" + elem + "](v, conv.WithTrimSpace(), conv.WithIgnoreEmpty()); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindSlice, v, err) }; dst." + field + " = x\n")
				return
			}
		}
		b.WriteString("x, err := conv.Convert[" + ts + "](v); if err != nil { return conv.PathError(\"" + field + "\", conv.KindOf(v), conv.KindInvalid, v, err) }; dst." + field + " = x\n")
	}
}
func isTarget(s string) bool {
	switch s {
	case "bool", "string", "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "float32", "float64", "time.Duration", "time.Time":
		return true
	}
	return false
}
func tagName(f *ast.Field, fallback string) string {
	if f.Tag == nil {
		return fallback
	}
	raw, _ := strconv.Unquote(f.Tag.Value)
	tag := reflectTagGet(raw, "convert")
	if tag == "-" {
		return fallback
	}
	if tag != "" {
		return strings.Split(tag, ",")[0]
	}
	return fallback
}
func defaultTag(f *ast.Field) string {
	if f.Tag == nil {
		return ""
	}
	raw, _ := strconv.Unquote(f.Tag.Value)
	return reflectTagGet(raw, "default")
}
func reflectTagGet(tag, key string) string {
	for tag != "" {
		tag = strings.TrimLeft(tag, " ")
		if tag == "" {
			break
		}
		i := strings.Index(tag, ":\"")
		if i < 0 {
			break
		}
		name := tag[:i]
		tag = tag[i+2:]
		j := strings.IndexByte(tag, '"')
		if j < 0 {
			break
		}
		val := tag[:j]
		tag = tag[j+1:]
		if name == key {
			return val
		}
	}
	return ""
}
func exprString(e ast.Expr) string {
	switch x := e.(type) {
	case *ast.Ident:
		return x.Name
	case *ast.SelectorExpr:
		return exprString(x.X) + "." + x.Sel.Name
	case *ast.ArrayType:
		return "[]" + exprString(x.Elt)
	case *ast.StarExpr:
		return "*" + exprString(x.X)
	}
	return "any"
}
func snakeNameLocal(s string) string {
	var b strings.Builder
	for i, c := range s {
		if c >= 'A' && c <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			c += 'a' - 'A'
		}
		b.WriteRune(c)
	}
	return b.String()
}
func escape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	return strings.ReplaceAll(s, "\"", "\\\"")
}
