package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	typeName := flag.String("type", "", "struct type name to generate converter for")
	input := flag.String("input", "", "Go source file containing the struct; defaults to files in current package")
	out := flag.String("out", "", "output file; defaults to convert_<type>_gen.go")
	convertImport := flag.String("convert-import", "github.com/oarkflow/convert", "import path for convert package")
	flag.Parse()
	if *typeName == "" {
		fatal("-type is required")
	}
	files := []string{}
	if *input != "" {
		files = append(files, *input)
	} else {
		files = append(files, flag.Args()...)
	}
	if len(files) == 0 {
		fatal("provide -input or source files")
	}
	pkg, fields, err := findStruct(files, *typeName)
	if err != nil {
		fatal(err.Error())
	}
	if *out == "" {
		*out = "convert_" + strings.ToLower(*typeName) + "_gen.go"
	}
	src, err := generate(pkg, *typeName, fields, *convertImport)
	if err != nil {
		fatal(err.Error())
	}
	if err := os.WriteFile(*out, src, 0644); err != nil {
		fatal(err.Error())
	}
}

func fatal(msg string) { fmt.Fprintln(os.Stderr, "convertgen:", msg); os.Exit(1) }

type field struct{ Name, Key string }

func findStruct(files []string, typeName string) (string, []field, error) {
	fset := token.NewFileSet()
	pkg := ""
	fields := []field{}
	for _, file := range files {
		f, err := parser.ParseFile(fset, file, nil, parser.ParseComments)
		if err != nil {
			return "", nil, err
		}
		if pkg == "" {
			pkg = f.Name.Name
		}
		for _, decl := range f.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || ts.Name.Name != typeName {
					continue
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return "", nil, fmt.Errorf("%s is not a struct", typeName)
				}
				for _, fl := range st.Fields.List {
					if len(fl.Names) == 0 {
						continue
					}
					for _, n := range fl.Names {
						if !n.IsExported() {
							continue
						}
						key := snake(n.Name)
						if fl.Tag != nil {
							tag := strings.Trim(fl.Tag.Value, "`")
							if v := tagValue(tag, "convert"); v != "" && v != "-" {
								key = v
							}
						}
						fields = append(fields, field{Name: n.Name, Key: key})
					}
				}
				return pkg, fields, nil
			}
		}
	}
	return "", nil, fmt.Errorf("type %s not found", typeName)
}

func tagValue(tag, name string) string {
	for _, part := range strings.Split(tag, " ") {
		if strings.HasPrefix(part, name+":\"") {
			v := strings.TrimPrefix(part, name+":\"")
			return strings.TrimSuffix(v, "\"")
		}
	}
	return ""
}
func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			r += 'a' - 'A'
		}
		b.WriteRune(r)
	}
	return b.String()
}

func generate(pkg, typeName string, fields []field, convertImport string) ([]byte, error) {
	var b strings.Builder
	b.WriteString("// Code generated by convertgen; DO NOT EDIT.\n")
	b.WriteString("package ")
	b.WriteString(pkg)
	b.WriteString("\n\n")
	b.WriteString("import convert \"")
	b.WriteString(convertImport)
	b.WriteString("\"\n\n")
	b.WriteString("func Populate")
	b.WriteString(typeName)
	b.WriteString("(dst *")
	b.WriteString(typeName)
	b.WriteString(", src map[string]any) error {\n")
	b.WriteString("\tif dst == nil { return convert.ErrNil }\n")
	for _, f := range fields {
		b.WriteString("\tif v, ok := src[\"")
		b.WriteString(f.Key)
		b.WriteString("\"]; ok { if err := convert.AsInto(v, &dst.")
		b.WriteString(f.Name)
		b.WriteString("); err != nil { return err } }\n")
	}
	b.WriteString("\treturn nil\n}\n")
	return format.Source([]byte(b.String()))
}
